version: '3.9'

x-app: &main-app
  build:
    context: .
    dockerfile: Dockerfile
    target: development
  volumes:
    - ./:/opt/app
    - app_statics:/var/www/static
  env_file:
    - .env

services:
  web:
    <<: *main-app
    ports:
      - 8000:8000

volumes:
  app_statics:
