# Generated by Django 5.0 on 2024-02-18 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanomien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date_joined', models.DateField()),
                ('favourite_language', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('jv', 'Java'), ('csh', 'C#'), ('vb', '.Net'), ('cpp', 'C++'), ('go', 'Go'), ('rb', 'Ruby')], max_length=10)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('sherpa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trekkers', to='tribu.kanomien')),
            ],
        ),
    ]
